retrive dependancy, and push crap in ~/bin
Signed-off-by: Matthias Gatto <matthias.gatto@outscale.com>

diff --git a/osc-pony b/osc-pony
--- a/osc-pony
+++ b/osc-pony
@@ -1,5 +1,34 @@
 #!/bin/bash
 
+if [ ! -d "$HOME/bin/" ]; then
+    echo "~/bin/ is required"
+    exit 1
+fi
+
+export PATH="$HOME/bin/:$PATH"
+
+wget_bin()
+{
+    URL=$1
+    BIN_NAME=$(basename $URL)
+    DST_NAME=~/bin/$BIN_NAME
+
+    if [ -x $DST_NAME ]; then
+        return
+    fi
+
+    wget $URL -P ~/bin/
+    chmod +x $DST_NAME
+}
+
+wget_bin "https://github.com/outscale-mgo/json-array-object/releases/download/0.1.0/json-array-x86_64.AppImage"
+wget_bin "https://github.com/outscale-mgo/json-array-object/releases/download/0.1.0/json-object-x86_64.AppImage"
+wget_bin "https://github.com/cosmo-ray/json-search/releases/download/0.1/json-search-x86_64.AppImage"
+
+alias json-array=json-array-x86_64.AppImage
+alias json-object=json-object-x86_64.AppImage
+alias json-search=json-search-x86_64.AppImage
+
 oscp_retrive_ak()
 {
     TW=$(($(tput cols) - 4))
